name: Sarathi APK Builder
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Build APK with Buildozer
        run: |
          # पुराना कचरा साफ़ करके नए सिरे से (Debug Level 2 के साथ) बिल्ड करेंगे
          buildozer -v android clean
          buildozer -v android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sarathi-App
          path: bin/*.apk



